version: '3.8'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.11
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - vllm-network

  vllm:
    container_name: vllm
    image: vllm-kimi-k2:latest
    build: .
    env_file: .env
    volumes:
      - ./models:/models
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vllm.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.vllm.entrypoints=websecure"
      - "traefik.http.routers.vllm.tls.certresolver=myresolver"
      - "traefik.http.services.vllm.loadbalancer.server.port=8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    shm_size: 32gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - vllm-network
    restart: unless-stopped

networks:
  vllm-network:
    driver: bridge